service: template-builder

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn

functions:
  LambdaFunction:
    handler: src/index.handler
    events:
      - http:
          method: get
          path: /
