const {
    REACT_APP_INACTIVITY_TIMEOUT = 10,
    REACT_APP_LOGOUT_COUNTDOWN_TIME = 5,
} = process.env;

export const INACTIVITY_TIMEOUT = +REACT_APP_INACTIVITY_TIMEOUT;
export const LOGOUT_COUNTDOWN_TIME = +REACT_APP_LOGOUT_COUNTDOWN_TIME;
